### PR TITLE
docker setup for main nightlies

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Review by PeterAdams-A — APPROVED** [review]
Great change

**Review by Lukasa — APPROVED** [review]

**Comment by yim-lee** [comment]
I set up https://ci.swiftserver.group/job/swift-nio-extras-swift-nightly-prb/ but it's disabled for now. PLMK if you need it enabled or add other job(s).

**Comment by weissi** [comment]
@yim-lee thank you! I think you could enable the `main` nightly job now, I'd expect it to work with this PR

**Comment by yim-lee** [comment]
> I think you could enable the main nightly job now

@weissi 👍 enabled

**Pull request merged**
