### PR TITLE
Renames the files for the frame decoder classes to match the class names.

### PR DESCRIPTION
**Pull request by tigerpixel**
Renames the files for the frame decoder classes to match the class names.

### Motivation:

Neatening of the project by ensuring file names match the contained class names.

### Modifications:

5 file renames, 4 of which are test files.
Ruby hooks script ran with no changes.

### Result:

The project is a little neater.

### CODE REVIEW

**Comment by tigerpixel** [comment]
Hello. Sorry, this is a bit trivial. I wanted to contribute a bit more to this project and thought I would go with a small contribution first, just to get into the swing of it. Thanks.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Comment by Lukasa** [comment]
You do need to run the Linux test generation script, however, as you've renamed some of the test files.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please

**Pull request merged**
