### PR TITLE
Add `fflush(stdout)` to DebugInbound/OutboundEventsHandlers

### PR DESCRIPTION
**Pull request by NicolasCombe5555**
Added `fflush(stdout)` to `DebugInboundEventsHandler` and `DebugOutboundEventsHandler` concerning #121 

### Motivation:

Contribute with my first issue 🚀

### Modifications:

Added `fflush(stdout)` to `DebugInboundEventsHandler.swift` and `DebugOutboundEventsHandler.swift`

### Result:

We will make sure that the stdout buffer is always flushed even in production when writing to pipes.

### Additional comments:

Hello 👍🏻 im not sure if this is all we need, just let me know. Thank you for leaving this `good first issue` open 👍🏻.

### CODE REVIEW

**Comment by glbrntt** [comment]
@swift-nio-bot test this please

**Review by glbrntt — APPROVED** [review]
Looks good, thank you @NicolasCombe555

**Comment by glbrntt** [comment]
@swift-nio-bot test this please

**Comment by fabianfett** [comment]
@swift-nio-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@glbrntt @fabianfett please use "swift-server-bot"

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@NicolasCombe5555 no, CI trouble

**Comment by glbrntt** [comment]
@swift-server-bot test this please

**Review by Lukasa — APPROVED** [review]

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Pull request merged**
